export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';

export const SIGN_UP = 'SIGN_UP';

export const NAVIGATION_LOGIN = 'NAVIGATION_LOGIN';
export const NAVIGATION_SIGNUP = 'NAVIGATION_SIGNUP';
export const NAVIGATION_SCAN_ID = 'NAVIGATION_SCAN_ID';
export const NAVIGATION_SCAN_QR = 'NAVIGATION_SCAN_QR';